require('dotenv').config();
const fs = require('fs');


const ARENA_PAT = process.env.ARENA_PAT;
const ABOUT_CHANNEL = 'portfolio-about-me';
const PHOTO_CHANNEL = 'portfolio-photography-gallery';
const EDITORIAL_CHANNEL = 'portfolio-editorial-phzbw5s5xrm';
const IN_PROGRESS_CHANNEL = 'portfolio-editorial-in-progress';

const headers = {
    'Authorization': `Bearer ${ARENA_PAT}`,
    'Accept': 'application/json'
};

async function fetchArena(endpoint) {
    const url = `https://api.are.na/v3/${endpoint}`;
    console.log(`Fetching: ${url}`);
    const res = await fetch(url, { headers });
    if (!res.ok) {
        throw new Error(`Failed to fetch ${url}: ${res.statusText}`);
    }
    return res.json();
}

async function fetchAllArenaContents(channelSlug) {
    let allContents = [];
    let page = 1;
    let per = 100;
    let hasMore = true;

    while (hasMore) {
        const data = await fetchArena(`channels/${channelSlug}/contents?per=${per}&page=${page}`);
        const contents = data.contents || data.data || [];
        allContents = allContents.concat(contents);

        if (contents.length < per) {
            hasMore = false;
        } else {
            page++;
        }
    }
    return allContents;
}

function formatProjectDescription(description) {
    if (!description) return '';
    description = description.trim();
    if (/<p[ >]/i.test(description)) {
        return description.replace(/>\s+</g, '><');
    }
    const paragraphs = description.split(/\n\s*\n/).filter(Boolean);
    if (paragraphs.length > 1) {
        return paragraphs.map(p => `<p>${p.trim().replace(/\n/g, '<br>')}</p>`).join('');
    }
    return `<p>${description.replace(/\n/g, '<br>')}</p>`;
}

function formatImageDescription(rawDesc) {
    if (!rawDesc) return '';
    let desc = typeof rawDesc === 'string' ? rawDesc : (rawDesc.plain || rawDesc.markdown || rawDesc.html || '');
    desc = desc.trim();
    if (!desc) return '';

    // Clean double markdown links like [http://...](http://...)
    desc = desc.replace(/\[(https?:\/\/[^\]\s]+)\]\s*\(\1\)/g, '$1');

    // 1. Convert markdown links [Text](URL) or [Text] (URL)
    desc = desc.replace(/\[(.*?)\]\s*\((https?:\/\/[^\s\)]+)\)/g, (match, text, url) => {
        return `<a href="${url}" target="_blank" class="credit-name">${text.trim()}</a>`;
    });

    // 2. Convert Name (https://...) where URL is in parentheses
    desc = desc.replace(/(^|[\s\n])([^\n<]+?)\s*\((https?:\/\/[^\s\)]+)\)/g, (match, prefix, text, url) => {
        const cleanText = text.trim();
        const lower = cleanText.toLowerCase();
        if (lower.startsWith('picture taken by ') || lower.startsWith('photo taken by ')) {
            const labelMatch = cleanText.match(/^(Picture|Photo)\s+taken\s+by\s+(.*)/i);
            if (labelMatch) {
                return `${prefix}<span class="credit-label">${labelMatch[1]} taken by</span> <a href="${url}" target="_blank" class="credit-name">${labelMatch[2].trim()}</a>`;
            }
        }
        return `${prefix}<a href="${url}" target="_blank" class="credit-name">${cleanText}</a>`;
    });

    // 3. Format "Picture/Photo taken by Name" if not yet formatted as a link
    desc = desc.replace(/(Picture|Photo)\s+taken\s+by\s+([^<\n]+)/gi, (match, label, name) => {
        return `<span class="credit-label">${label} taken by</span> <span class="credit-name">${name.trim()}</span>`;
    });

    // 4. Handle "Picture/Photo taken by <a ...>" where <a> was already generated by step 1
    desc = desc.replace(/(Picture|Photo)\s+taken\s+by\s+(<a\s+[^>]*?>.*?<\/a>)/gi, (match, label, aTag) => {
        return `<span class="credit-label">${label} taken by</span> ${aTag}`;
    });

    // 5. Ensure any existing <a> tags have proper class and target
    desc = desc.replace(/<a\s+([^>]*?)>/gi, (m, attrs) => {
        let newAttrs = attrs;
        if (!newAttrs.includes('target=')) newAttrs += ' target="_blank"';
        if (!newAttrs.includes('class=')) newAttrs += ' class="credit-name"';
        return `<a ${newAttrs}>`;
    });

    // Replace newlines inside description with <br> if multi-line
    desc = desc.replace(/\n/g, '<br>');

    // If description doesn't already start with <span, wrap the outer container
    if (!desc.startsWith('<span class="credit-label">') && !desc.startsWith('<span class="image-credit">')) {
        return `<span class="image-credit"><span class="credit-label">${desc}</span></span>`;
    }
    return `<span class="image-credit">${desc}</span>`;
}

function isVideoItem(item) {
    if (!item) return false;
    const url = (item.attachment?.url || item.embed?.url || item.source?.url || '').toLowerCase();
    const contentType = (item.attachment?.content_type || '').toLowerCase();
    if (contentType.startsWith('video/') || /\.(mp4|mov|webm|m4v)(\?.*)?$/i.test(url)) {
        return true;
    }
    if (item.type === 'Media' || item.type === 'Attachment') {
        if (contentType.startsWith('video/') || /\.(mp4|mov|webm|m4v)(\?.*)?$/i.test(url)) {
            return true;
        }
    }
    return false;
}

function getHighResUrl(item) {
    if (!item || !item.image) return '';
    // item.image.src is the 100% uncompressed full-resolution original CloudFront URL in Are.na API
    if (item.image.src && typeof item.image.src === 'string') {
        return item.image.src;
    }
    if (item.image.original && (item.image.original.url || item.image.original.src)) {
        return item.image.original.url || item.image.original.src;
    }
    if (item.image.large && item.image.large.src) {
        return item.image.large.src;
    }
    return '';
}

async function build() {
    try {
        console.log('Starting Are.na Build Process...');
        let template = fs.readFileSync('template.html', 'utf-8');

        const aboutContents = await fetchAllArenaContents(ABOUT_CHANNEL);
        const aboutTextItem = aboutContents.find(item => item.type === 'Text');
        const aboutHTML = aboutTextItem && aboutTextItem.content ? (aboutTextItem.content.html || aboutTextItem.content.plain || '') : 'About me text not found.';
        template = template.replace('{{ABOUT_ME}}', aboutHTML);

        // --- FETCH IN-PROGRESS TAGS ---
        let inProgressSlugs = new Set();
        try {
            const inProgressContents = await fetchAllArenaContents(IN_PROGRESS_CHANNEL);
            inProgressSlugs = new Set(inProgressContents.map(item => item.slug));
            console.log(`Found ${inProgressSlugs.size} in-progress projects.`);
        } catch (err) {
            console.log(`Warning: Could not fetch In Progress channel: ${err.message}`);
        }

        // --- EDITORIAL SECTION (Fetch first to build image map) ---
        let projectLinksHTML = '';
        let carouselsHTML = '';
        const imageToProjectMap = {}; // Map image IDs to project info

        try {
            const editorialContents = await fetchAllArenaContents(EDITORIAL_CHANNEL);
            const projectChannels = editorialContents.filter(item => {
                const isChannel = item.type === 'Channel';
                const description = item.description ? (item.description.plain || item.description.markdown || '') : '';
                const isNotDraft = !description.toLowerCase().includes('[draft]');
                return isChannel && isNotDraft;
            });

            for (let i = 0; i < projectChannels.length; i++) {
                const project = projectChannels[i];
                const projId = project.slug;
                const isFirst = i === 0;
                const isInProgress = inProgressSlugs.has(projId);

                const projContents = await fetchAllArenaContents(projId);
                const descItem = projContents.find(item => item.type === 'Text');
                const rawDescription = descItem && descItem.content ? (descItem.content.html || descItem.content.plain || '') : '';
                const formattedDesc = formatProjectDescription(rawDescription);
                const displayTitle = (descItem && descItem.title) ? descItem.title : project.title.replace(/^PORTFOLIO \/ /i, '');
                const mediaItems = projContents.filter(item => (item.type === 'Image' && item.image) || isVideoItem(item));

                // Map these items to this project
                mediaItems.forEach(item => {
                    imageToProjectMap[item.id] = { id: projId, title: displayTitle };
                });

                const labelHTML = isInProgress
                    ? '<span class="in_progress_label">In Progress...</span>'
                    : '<span class="about_button">?</span>';

                projectLinksHTML += `
                        <li ${isFirst ? 'class="active"' : ''} data-project="${projId}">
                            <span class="title-wrapper">
                                <span class="project_number">${i + 1}</span>
                                <span class="project_title">${displayTitle}</span>
                            </span>
                            ${labelHTML}
                            <span class="about_project">${isInProgress ? '' : formattedDesc}</span>
                        </li>`;

                let carouselImagesHTML = mediaItems.map((item, imgIndex) => {
                    const isVideo = isVideoItem(item);
                    const creditHTML = formatImageDescription(item.description);

                    if (isVideo) {
                        const videoUrl = item.attachment ? item.attachment.url : (item.embed ? item.embed.url : (item.source ? item.source.url : ''));
                        const posterUrl = getHighResUrl(item);
                        const posterAttr = posterUrl ? ` poster="${posterUrl}"` : '';

                        return `
                        <div class="carousel-item ${imgIndex === 0 ? 'active' : ''}">
                            <div class="image-container">
                                <video src="${videoUrl}"${posterAttr} autoplay muted loop playsinline disablePictureInPicture preload="auto" onloadstart="this.classList.add('loaded')" onloadeddata="this.classList.add('loaded')"></video>
                                ${creditHTML}
                            </div>
                        </div>`;
                    } else {
                        const imgUrl = item.image.medium ? item.image.medium.src : getHighResUrl(item);
                        return `
                        <div class="carousel-item ${imgIndex === 0 ? 'active' : ''}">
                            <div class="image-container">
                                <img src="${imgUrl}" onload="this.classList.add('loaded')">
                                ${creditHTML}
                            </div>
                        </div>`;
                    }
                }).join('\n');

                carouselsHTML += `
                <div id="carousel-${projId}" class="carousel ${isFirst ? 'active' : ''}">
                    <div class="carousel-inner">
${carouselImagesHTML}
                        <div class="carousel-counter"><div class="counter-track"></div></div>
                    </div>
                </div>`;
            }

            template = template.replace('{{EDITORIAL_PROJECT_LINKS}}', projectLinksHTML);
            template = template.replace('{{EDITORIAL_PROJECT_CAROUSELS}}', carouselsHTML);
        } catch (err) {
            console.log(`Skipping Editorial: ${err.message}`);
            template = template.replace('{{EDITORIAL_PROJECT_LINKS}}', '<!-- Editorial links pending -->');
            template = template.replace('{{EDITORIAL_PROJECT_CAROUSELS}}', '<!-- Editorial carousels pending -->');
        }

        // --- PHOTOGRAPHY SECTION (Use image map for linking) ---
        try {
            const photoContents = await fetchAllArenaContents(PHOTO_CHANNEL);
            const photoItems = photoContents.filter(item => item.type === 'Image');
            const totalCount = photoItems.length;
            const photosHTML = photoItems
                .map((item, index) => {
                    const smallUrl = item.image.small ? item.image.small.src : item.image.src;
                    const mediumUrl = item.image.medium ? item.image.medium.src : item.image.src;
                    const largeUrl = item.image.large ? item.image.large.src : item.image.src;
                    const originalUrl = getHighResUrl(item);
                    const projectInfo = imageToProjectMap[item.id];
                    // Ensure description is a string and handle nulls
                    const rawDesc = item.description || '';
                    const description = typeof rawDesc === 'string' ? rawDesc : (rawDesc.plain || '');

                    const dataAttrs = projectInfo
                        ? `data-project-id="${projectInfo.id}" data-project-title="${projectInfo.title}"`
                        : '';

                    const photoNum = totalCount - index;
                    return `                <div class="photo-item" ${dataAttrs} data-description="${description.replace(/"/g, '&quot;')}"><img src="${largeUrl}" srcset="${smallUrl} 400w, ${mediumUrl} 1200w, ${largeUrl} 1800w" sizes="(max-width: 768px) 50vw, 50vw" data-large="${originalUrl}" loading="lazy" onload="this.classList.add('loaded')"><span>${photoNum}</span></div>`;
                })
                .join('\n');

            template = template.replace('{{PHOTOGRAPHY_GALLERY}}', photosHTML);
        } catch (err) {
            console.log(`Skipping Photography: ${err.message}`);
            template = template.replace('{{PHOTOGRAPHY_GALLERY}}', '<!-- Photography channel pending -->');
        }

        const now = new Date();
        const buildYear = now.getFullYear();
        const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
        const buildMonth = monthNames[now.getMonth()];

        template = template.replace(/\{\{BUILD_YEAR\}\}/g, buildYear);
        template = template.replace('{{BUILD_MONTH}}', buildMonth);

        fs.writeFileSync('index.html', template);
        console.log('Build complete! index.html generated successfully.');

    } catch (error) {
        console.error('Build failed:', error);
        process.exit(1);
    }
}

build();
